#http://www.minecraftwiki.net/wiki/Data_values
blockids = {
	0	:"air",
	1	:"stone",
	2	:"grass",
	3	:"dirt",
	4	:"cobblestone",
	5	:"wood",
	6	:"sapling",
	7	:"bedrock",
	8	:"water",
	9	:"stationary water",
	10	:"lava",
	11	:"stationary lava",
	12	:"sand",
	13	:"gravel",
	14	:"gold ore",
	15	:"iron ore",
	16	:"coal ore",
	17	:"log",
	18	:"leaves",
	19	:"sponge",
	20	:"glass",
	21	:"red cloth",
	22	:"orange cloth",
	23	:"yellow cloth",
	24	:"lime cloth",
	25	:"green cloth",
	26	:"aqua green cloth",
	27	:"cyan cloth",
	28	:"blue cloth",
	29	:"purple cloth",
	30	:"indigo cloth",
	31	:"violet cloth",
	32	:"magenta cloth",
	33	:"pink cloth",
	34	:"black cloth",
	35	:"gray cloth / white cloth",
	36	:"white cloth",
	37	:"yellow flower",
	38	:"red rose",
	39	:"brown mushroom",
	40	:"red mushroom",
	41	:"gold block",
	42	:"iron block",
	43	:"double step",
	44	:"step",
	45	:"brick",
	46	:"tnt",
	47	:"bookshelf",
	48	:"mossy cobblestone",
	49	:"obsidian",
	50	:"torch",
	51	:"fire",
	52	:"mob spawner",
	53	:"wooden stairs",
	54	:"chest",
	55	:"redstone wire",
	56	:"diamond ore",
	57	:"diamond block",
	58	:"workbench",
	59	:"crops",
	60	:"soil",
	61	:"furnace",
	62	:"burning furnace",
	63	:"sign post",
	64	:"wooden door",
	65	:"ladder",
	66	:"minecart tracks",
	67	:"cobblestone stairs",
	68	:"wall sign",
	69	:"lever",
	70	:"stone pressure plate",
	71	:"iron door",
	72	:"wooden pressure plate",
	73	:"redstone ore",
	74	:"glowing redstone ore",
	75	:"redstone torch off",
	76	:"redstone torch on",
	77	:"stone button",
	78	:"snow",
	79	:"ice",
	80	:"snow block",
	81	:"cactus",
	82	:"clay",
	83	:"reed",
	84	:"jukebox",
	85	:"fence"
}

id2name = dict([(blockids[id], id) for id in blockids])
id2underName = dict([(blockids[id].replace(" ","_"), id) for id in blockids])

	